
syntax = "proto3";
option go_package = "RTVMandatoryActivity3/grpc/proto";

message Nothing {}

message ClientMessage {
    string name = 1;
    int32 lamport = 2;
    string message = 3;
}

message ClientJoins {
    string name = 1;
    int32 lamport = 2;
    string message = 3;
}

message ClientLeaves {
    string name = 1;
    int32 lamport = 2;
    string message = 3;
}

service ChitChat {
    rpc PublishMessage(ClientMessage) returns (ClientMessage);
    rpc PublishJoin(Nothing) returns (ClientJoins);
    rpc PublishLeave(Nothing) returns (ClientLeaves);
}